/**
 * Docs repository — the only place the docs module fetches its raw data.
 *
 * Three same-origin sources, all served by the instance behind the SPA:
 *   - `GET /openapi.json`            — the standards-pure OpenAPI document
 *   - `GET /reference/endpoints.json` — the canonical permission/typical-caller
 *     join (also carries the conceptual permission catalogue in its
 *     `permissions` section)
 *   - `GET /instance`                 — the advertised broker URL, swapped into
 *     the Broker spec's placeholder `servers`
 *
 * Plus two build-time static assets, served from the SPA's own origin:
 *   - `cli-reference.json` — the CLI command tree, generated from cobra by
 *     `make cli-reference`. Resolved relative to `document.baseURI` so it works
 *     under the `/app` mount prefix.
 *   - `broker-openapi.json` — the Broker (data-plane) OpenAPI document. The
 *     broker is a standalone service whose spec is never part of this instance's
 *     `/openapi.json`, so the docs render a committed artifact generated by
 *     `make broker-reference` from the hand-curated `openapi/broker` spec.
 *
 * These hardcode the live same-origin URLs. TODO: a portable/snapshot mode
 * could resolve these from the boot config (`/app-config.json`) so the
 * same build can render a committed snapshot; until then these are the live
 * endpoints (the dev server proxies both to the backend — see vite.config.ts).
 *
 * The two are kept independent on purpose: the API reference renders the spec
 * verbatim, and the permission/actor reference enriches each operation. They are
 * never merged.
 */
import { SystemService } from '@/shared/api';
import type { CliReference, OpenApiDocument, ReferencePayload } from '@/modules/docs/api/types';

const SPEC_URL = '/openapi.json';
const REFERENCE_URL = '/reference/endpoints.json';
const CLI_REFERENCE_URL = 'cli-reference.json';
const BROKER_SPEC_URL = 'broker-openapi.json';

async function getJson<T>(url: string): Promise<T> {
	const response = await fetch(url, { headers: { Accept: 'application/json' } });
	if (!response.ok) {
		throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
	}
	return (await response.json()) as T;
}

export function fetchOpenApiDocument(): Promise<OpenApiDocument> {
	return getJson<OpenApiDocument>(SPEC_URL);
}

export function fetchReferencePayload(): Promise<ReferencePayload> {
	return getJson<ReferencePayload>(REFERENCE_URL);
}

/**
 * Fetch the committed CLI reference. It is a build-time artifact (generated by
 * `make cli-reference` from the cobra command tree) served as a static asset
 * from the SPA's own origin, resolved relative to the app's base path so it
 * works under the `/app` prefix the SPA is mounted at.
 */
export function fetchCliReference(): Promise<CliReference> {
	return getJson<CliReference>(new URL(CLI_REFERENCE_URL, document.baseURI).toString());
}

/**
 * Fetch the committed Broker OpenAPI document. Like the CLI reference, this is a
 * build-time artifact (generated by `make broker-reference` from the
 * hand-curated `openapi/broker` spec) served as a static asset from the SPA's
 * own origin, resolved relative to the app's base path so it works under the
 * `/app` prefix. The broker runs as its own service, so its spec is never part
 * of this instance's `/openapi.json`.
 */
export function fetchBrokerSpec(): Promise<OpenApiDocument> {
	return getJson<OpenApiDocument>(new URL(BROKER_SPEC_URL, document.baseURI).toString());
}

/**
 * The broker URL this backend advertises on `GET /instance` (unauthenticated,
 * like the docs page), or `null` when it withholds one — absent on older
 * backends, or a loopback default on a remote install.
 */
export async function fetchAdvertisedBrokerUrl(): Promise<string | null> {
	const res = await SystemService.getInstance();
	return res.broker_url ?? null;
}
