"""Drift-guard + unit tests for the endpoint + permission reference generator.

``docs/reference/endpoints.{md,json}`` are generated by ``tools/endpoint_tree``
(``make endpoints``). These tests assert the committed artifacts match what the
generator produces today, and that the join/grouping/render logic behaves on
fixture endpoints, so the reference can't silently drift from code.

The join itself lives in ``jentic_one.shared.web.endpoint_reference`` (shared with
the live ``GET /reference/endpoints.json`` endpoint); the renderers live in
``tools.endpoint_tree``.
"""

from __future__ import annotations

import json
from dataclasses import asdict

import pytest
from fastapi import APIRouter, FastAPI
from tools.endpoint_tree import (
    ENDPOINTS_JSON,
    ENDPOINTS_MD,
    _build_broker_app,
    _build_control_app,
    collect,
    render_json,
    render_markdown,
)

from jentic_one.shared.models.actors import ActorType
from jentic_one.shared.web.deps import get_current_identity
from jentic_one.shared.web.endpoint_permissions import (
    _AGENT_DEFAULT_PERMISSIONS,
    _OPERATOR_PERMISSIONS,
    TYPICAL_OPERATOR,
    _closure_values,
    _typical_caller,
    build_operation_auth_map,
)
from jentic_one.shared.web.endpoint_reference import (
    GROUP_AGENT,
    GROUP_ANY,
    GROUP_OPERATOR,
    GROUP_PUBLIC,
    Endpoint,
    _annotate_broker,
    _declared_broker_endpoints,
    _endpoints_from_app,
    assert_broker_classification_is_sound,
    assert_classification_is_sound,
    build_reference_payload,
    collect_endpoints,
)


def _ep(
    method: str,
    path: str,
    *,
    authenticated: bool = True,
    public: bool = False,
    actor_types: list[str] | None = None,
    required_permissions: list[str] | None = None,
    typical_caller: str | None = None,
    auth_note: str | None = None,
    summary: str = "",
    operation_id: str | None = None,
    surface: str = "control",
) -> Endpoint:
    return Endpoint(
        method=method,
        path=path,
        surface=surface,
        summary=summary,
        operation_id=operation_id,
        authenticated=authenticated,
        public=public,
        actor_types=actor_types or [],
        required_permissions=required_permissions or [],
        typical_caller=typical_caller,
        auth_note=auth_note,
    )


@pytest.fixture()
def fixture_endpoints() -> list[Endpoint]:
    return [
        _ep(
            "GET",
            "/agents",
            actor_types=["user"],
            required_permissions=["agents:read"],
            typical_caller="operator",
            summary="List Agents",
            operation_id="listAgents",
        ),
        _ep(
            "POST",
            "/capabilities:execute",
            actor_types=["agent", "toolkit"],
            required_permissions=["capabilities:execute"],
            typical_caller="agent",
            summary="Execute",
            operation_id="execute",
        ),
        _ep(
            "POST",
            "/credentials",
            actor_types=["user", "agent", "toolkit"],
            required_permissions=[],
            typical_caller="any",
            summary="Create Credential",
            operation_id="createCredential",
        ),
        _ep(
            "POST",
            "/oauth/token",
            authenticated=False,
            public=True,
            summary="Token",
            operation_id="tokenEndpoint",
        ),
        _ep(
            "GET",
            "/register/{agent_id}",
            actor_types=["agent"],
            required_permissions=[],
            auth_note="Authenticated with the Registration-Access-Token.",
            summary="Poll registration status",
            operation_id="pollStatusEndpoint",
        ),
        _ep(
            "GET",
            "/health",
            authenticated=False,
            public=True,
            summary="Health",
            operation_id="getHealth",
        ),
    ]


@pytest.mark.arch
def test_grouping_by_typical_caller(fixture_endpoints: list[Endpoint]) -> None:
    by_path = {(e.method, e.path): e for e in fixture_endpoints}
    assert by_path[("GET", "/agents")].group == GROUP_OPERATOR
    assert by_path[("POST", "/capabilities:execute")].group == GROUP_AGENT
    assert by_path[("POST", "/credentials")].group == GROUP_ANY
    assert by_path[("GET", "/health")].group == GROUP_PUBLIC


@pytest.mark.arch
def test_explicit_public_is_public(fixture_endpoints: list[Endpoint]) -> None:
    """A public operation is never grouped as "any authenticated"."""
    by_path = {(e.method, e.path): e for e in fixture_endpoints}
    token = by_path[("POST", "/oauth/token")]
    assert token.public is True
    assert token.authenticated is False
    assert token.group == GROUP_PUBLIC


@pytest.mark.arch
def test_auth_note_recovered_and_rendered(fixture_endpoints: list[Endpoint]) -> None:
    by_path = {(e.method, e.path): e for e in fixture_endpoints}
    poll = by_path[("GET", "/register/{agent_id}")]
    assert poll.authenticated is True
    assert poll.auth_note and "Registration-Access-Token" in poll.auth_note
    md = render_markdown(fixture_endpoints)
    assert "Registration-Access-Token" in md


@pytest.mark.arch
def test_typical_caller_rendered(fixture_endpoints: list[Endpoint]) -> None:
    """The advisory typical-caller hint is shown as a column, framed as advisory."""
    md = render_markdown(fixture_endpoints)
    assert "Typical caller" in md
    # The hint must be advisory, never presented as an enforced restriction.
    assert "advisory hint" in md


@pytest.mark.arch
def test_classification_guard_rejects_undeclared_public() -> None:
    """A non-public-declared op rendered public must trip the fail-loud guard."""
    authed = [
        _ep("GET", f"/thing/{i}", actor_types=["user"], operation_id=f"thing{i}") for i in range(12)
    ]
    leaked = _ep(
        "POST",
        "/secret",
        authenticated=False,
        public=True,
        operation_id="secretOp",
        summary="Leaked",
    )
    with pytest.raises(RuntimeError, match="failed open"):
        assert_classification_is_sound([*authed, leaked], frozenset({"getHealth"}))


@pytest.mark.arch
def test_classification_guard_rejects_empty_recovery() -> None:
    """If almost nothing authenticates, introspection likely broke — fail loudly."""
    public_health = _ep(
        "GET",
        "/health",
        authenticated=False,
        public=True,
        operation_id="getHealth",
        summary="Health",
    )
    with pytest.raises(RuntimeError, match="permission introspection likely broke"):
        assert_classification_is_sound([public_health], frozenset({"getHealth"}))


@pytest.mark.arch
def test_broker_guard_allows_known_probes() -> None:
    """The broker's liveness/readiness probes may legitimately be public."""
    broker = [
        _ep("GET", "/health", authenticated=False, public=True, surface="broker"),
        _ep("GET", "/ready", authenticated=False, public=True, surface="broker"),
        _ep(
            "POST",
            "/{upstream_url}",
            required_permissions=["capabilities:execute"],
            typical_caller="agent",
            surface="broker",
        ),
    ]
    # No exception: only the known probes are public.
    assert_broker_classification_is_sound(broker)


@pytest.mark.arch
def test_broker_guard_rejects_unexpected_public_route() -> None:
    """An unexpected public broker route (not a probe, not the proxy) must fail loud."""
    broker = [
        _ep("GET", "/health", authenticated=False, public=True, surface="broker"),
        _ep(
            "GET",
            "/metrics",
            authenticated=False,
            public=True,
            operation_id="brokerMetrics",
            surface="broker",
        ),
    ]
    with pytest.raises(RuntimeError, match=r"broker operation.*classified public"):
        assert_broker_classification_is_sound(broker)


@pytest.mark.arch
def test_permissions_present(fixture_endpoints: list[Endpoint]) -> None:
    by_path = {(e.method, e.path): e for e in fixture_endpoints}
    assert by_path[("GET", "/agents")].required_permissions == ["agents:read"]
    assert by_path[("POST", "/credentials")].required_permissions == []
    assert by_path[("GET", "/health")].public is True


@pytest.mark.arch
def test_json_is_portable_and_valid(fixture_endpoints: list[Endpoint]) -> None:
    payload = build_reference_payload(fixture_endpoints)
    assert payload["schema"] == "jentic.endpoint-permission-tree/v1"
    assert payload["total"] == len(fixture_endpoints)
    # Every endpoint carries the fields a downstream consumer (CLI, SPA) needs.
    for ep in payload["endpoints"]:
        assert {"method", "path", "actor_types", "required_permissions", "group"} <= ep.keys()


@pytest.mark.arch
def test_markdown_renders_all_groups(fixture_endpoints: list[Endpoint]) -> None:
    md = render_markdown(fixture_endpoints)
    assert "DO NOT EDIT" in md
    assert GROUP_AGENT in md and GROUP_OPERATOR in md and GROUP_ANY in md and GROUP_PUBLIC in md


@pytest.mark.arch
def test_identity_dependency_recognition_is_qualname_scoped() -> None:
    """Only the real get_current_identity closure is treated as the auth dep.

    A same-named free variable on an unrelated dependency factory must NOT be
    misclassified as authentication (this is a security classification path).
    """
    # The genuine identity dependency is recognised, with its permission/actor read off.
    real_dep = get_current_identity(
        required_permissions=["agents:read"], require_actor_type=ActorType.AGENT
    ).dependency
    is_identity, perms, actor = _closure_values(real_dep)
    assert is_identity is True
    assert perms == ["agents:read"]
    assert actor is ActorType.AGENT

    # An impostor closing over identically-named freevars is NOT the identity dep.
    def _make_impostor() -> object:
        required_permissions = ["org:admin"]
        require_actor_type = ActorType.USER

        def _other_dependency() -> None:
            _ = (required_permissions, require_actor_type)

        return _other_dependency

    assert _closure_values(_make_impostor()) == (False, None, None)


def test_prefixed_included_router_keyed_by_full_path() -> None:
    """A router included under a prefix is keyed by its FULL path in the auth map.

    Regression for the ``AppContainer.extra_routers`` case (e.g. an enterprise
    overlay's ``/enterprise/admin/*`` console): ``include_router(prefix=...)`` wraps
    the router in a FastAPI ``_IncludedRouter`` whose child routes carry only their
    own (prefix-stripped) ``.path``. If the introspection walk drops that prefix,
    the auth map is keyed by the stripped path, fails to join the OpenAPI document
    (which uses the full path), and the endpoint reference mis-classifies the route
    as public — tripping ``assert_classification_is_sound`` with a 500. The walk
    must reconstruct the prefix so the permission is recovered under the full path.
    """
    router = APIRouter()

    @router.get("/toolkits/{toolkit_id}/shares", operation_id="prefixedListShares")
    async def _list_shares(
        toolkit_id: str,
        _identity: object = get_current_identity(required_permissions=["toolkits:write"]),
    ) -> dict[str, str]:
        return {"toolkit_id": toolkit_id}

    app = FastAPI()
    app.include_router(router, prefix="/enterprise/admin")

    auth_map = build_operation_auth_map(app)

    full_key = ("GET", "/enterprise/admin/toolkits/{toolkit_id}/shares")
    stripped_key = ("GET", "/toolkits/{toolkit_id}/shares")
    assert full_key in auth_map, (
        "prefixed included route must be keyed by its FULL path so it joins the "
        f"OpenAPI document; got keys {sorted(auth_map)}"
    )
    assert stripped_key not in auth_map, "route must NOT be keyed by the prefix-stripped path"
    entry = auth_map[full_key]
    assert entry["authenticated"] is True
    assert entry["permissions"] == ["toolkits:write"]


@pytest.mark.arch
def test_committed_reference_matches_generated() -> None:
    """docs/reference/endpoints.{md,json} must equal what the generator produces.

    Regenerate with ``make endpoints`` and commit the result.
    """
    endpoints = collect()

    expected_md = render_markdown(endpoints)
    actual_md = ENDPOINTS_MD.read_text(encoding="utf-8")
    assert actual_md == expected_md, (
        "docs/reference/endpoints.md is out of date with the code. "
        "Regenerate with `make endpoints` and commit the result."
    )

    expected_json = json.loads(render_json(endpoints))
    actual_json = json.loads(ENDPOINTS_JSON.read_text(encoding="utf-8"))
    assert actual_json == expected_json, (
        "docs/reference/endpoints.json is out of date with the code. "
        "Regenerate with `make endpoints` and commit the result."
    )


@pytest.mark.arch
def test_declared_broker_surface_matches_real_broker_app() -> None:
    """The declared broker surface must match the real broker app's routes.

    The live ``GET /reference/endpoints.json`` is mounted only on the control-plane
    app and cannot introspect the broker (it runs as a separate process), so the
    broker surface is declared in ``endpoint_reference`` and used when no broker app
    is passed. This builds the real broker app and asserts the declaration matches
    it exactly, so the declaration cannot silently drift from the broker.
    """
    introspected = _endpoints_from_app(_build_broker_app(), "broker")
    _annotate_broker(introspected)
    declared = _declared_broker_endpoints()

    def _sorted(eps: list[Endpoint]) -> list[dict[str, object]]:
        return sorted((asdict(e) for e in eps), key=lambda d: (d["path"], d["method"]))

    assert _sorted(introspected) == _sorted(declared), (
        "Declared broker surface (_declared_broker_endpoints) drifted from the real "
        "broker app. Update the declaration in endpoint_reference.py."
    )
    # Guard against a no-op (e.g. both empty) silently passing.
    assert {(e.path, e.method) for e in declared} >= {("/{upstream_url}", "POST")}


@pytest.mark.arch
def test_live_reference_matches_committed() -> None:
    """The live endpoint payload (broker=None) must equal the committed file.

    ``reference_router`` calls ``collect_endpoints(app)`` with no broker app, so this
    reproduces exactly what the live ``GET /reference/endpoints.json`` serves and
    asserts it equals the committed ``docs/reference/endpoints.json`` the docs SPA
    and CLI render — catching live-vs-committed drift (notably the broker surface).
    """
    live_payload = build_reference_payload(collect_endpoints(_build_control_app()))
    committed = json.loads(ENDPOINTS_JSON.read_text(encoding="utf-8"))
    committed.pop("_generated", None)
    assert live_payload == committed, (
        "Live GET /reference/endpoints.json (broker=None) differs from committed "
        "docs/reference/endpoints.json. The broker surface declaration or the "
        "committed file is stale; run `make endpoints` and reconcile."
    )


@pytest.mark.arch
def test_overlays_confirm_classified_operator() -> None:
    """overlays:confirm gates an operator route — the advisory hint must say so.

    Regression: overlays:confirm was added to the permission catalogue but not to
    _OPERATOR_PERMISSIONS, so the reference flipped the confirm endpoint's typical
    caller from "operator" to "any" — contradicting the PR's operator intent. Pin it.
    """
    assert _typical_caller(["overlays:confirm"], []) == TYPICAL_OPERATOR


@pytest.mark.arch
def test_operator_only_permissions_are_classified_operator() -> None:
    """Any permission withheld from agent defaults must classify as operator.

    The _typical_caller operator list is hand-maintained, which is exactly how
    overlays:confirm silently drifted to "any". This ties the classifier to the
    authorization model: a permission that is not an agent default (and isn't the
    org:admin superuser or an owner-scoped read) is, by definition,
    operator-held — so it must be in _OPERATOR_PERMISSIONS or the reference will
    mislabel its endpoints. (Theme 7 removed the self-service grant tier, so
    "self-service-grantable" no longer subtracts anything here.)
    """
    operator_only = {p for p in _OPERATOR_PERMISSIONS if p not in _AGENT_DEFAULT_PERMISSIONS}
    # Sanity: the set is non-trivial (guards against a vacuous pass).
    assert "overlays:confirm" in operator_only
    # Every such permission classifies as operator on its own.
    for permission in operator_only:
        assert _typical_caller([permission], []) == TYPICAL_OPERATOR, permission


@pytest.mark.arch
def test_no_service_account_surface_survives() -> None:
    """Theme-8 Phase 2: no route creates, lists, mutates, or mints for an SA.

    Walks the live combined control app's route table (the same one the
    reference is built from): no ``/service-accounts`` path, no
    ``/oauth/mint``, and no endpoint advertises ``service_account`` as a
    caller actor type.
    """
    app = _build_control_app()
    paths = {getattr(r, "path", "") for r in app.routes}
    assert not [p for p in paths if p.startswith("/service-accounts")]
    assert "/oauth/mint" not in paths
    for ep in collect_endpoints(app):
        assert "service_account" not in ep.actor_types, (ep.method, ep.path)
